# Generated by Django 4.2.3 on 2023-09-18 19:42

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='tourmodel',
            name='created_at',
            field=models.DateField(default=datetime.datetime(2023, 9, 18, 19, 42, 52, 425213, tzinfo=datetime.timezone.utc)),
        ),
        migrations.AddField(
            model_name='tourmodel',
            name='updated_at',
            field=models.DateField(default=datetime.datetime(2023, 9, 18, 19, 42, 52, 425213, tzinfo=datetime.timezone.utc)),
        ),
        migrations.AlterField(
            model_name='tourmodel',
            name='end_date',
            field=models.DateField(default=datetime.datetime(2023, 9, 18, 19, 42, 52, 425213, tzinfo=datetime.timezone.utc)),
        ),
        migrations.AlterField(
            model_name='tourmodel',
            name='start_date',
            field=models.DateField(default=datetime.datetime(2023, 9, 18, 19, 42, 52, 425213, tzinfo=datetime.timezone.utc)),
        ),
    ]
